services:
    SuperrbKunstmaanCompanyBundle.menu.adaptor.company:
        class: Superrb\KunstmaanCompanyBundle\Helper\Menu\CompanyMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
    SuperrbKunstmaanCompanyBundle.company.twig_extension:
        class: Superrb\KunstmaanCompanyBundle\Extension\CompanyTwigExtension
        arguments: ["@doctrine.orm.entity_manager", "@templating.engine.twig"]
        tags:
            - { name: twig.extension }